<?php

namespace app\admin\controller;

use think\Controller;
use think\Exception;
use think\Request;

class Goods extends Controller
{
    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkJWT();
    }

    public function index()
    {
        //
        try{
            $data=$this->request->get();
            if(isset($data['page'])&&!empty($data['page'])){
                $page=$data['page'];
            }else{
                $page=1;
            }

            if(isset($data['limit'])&&!empty($data['limit'])){
                $limit=$data['limit'];
            }else{
                $limit=1;
            }

            $sarr=[];
            if(!empty($data['gname'])){
              $sarr['gname']=['like','%'.$data['gname'].'%'];
            }

            if(!empty($data['ename'])){
                $sarr['ename']=['like','%'.$data['ename'].'%'];
            }
            if(!empty($data['lowprice'])&&!empty($data['highprice'])){
                $sarr['price']=[
                    ['>',$data['lowprice']],
                    ['<',$data['highprice']]
                ];
            }
            if(isset($data['typeid'])&&$data['typeid']!=0){
                $sarr['cid']=$data['typeid'];
            }
//            if(!empty($data['typeid'])){
//                $sarr['cid']=$data['typeid'];
//
//            }
            $model=model('Goods');
            $result=$model->querys($limit,$sarr,$page);
            $results=$result->items();
            $total=$result->total();
            if($results){
                return json([
                    'code'=>config('code.success'),
                    'msg'=>'商品获取成功',
                    'data'=>$results,
                    'total'=>$total
                ]);
            }else{
                return json([
                    'code'=>config('code.success'),
                    'msg'=>'暂无商品',
                    'data'=>[]
                ]);
            }
        }catch (Exception $exception){
            return json([
                'code'=>config('code.fail'),
                'msg'=>'获取商品失败',
            ]);
        }

    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
    //

    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
        $data=$this->request->post();
        $model=model('Goods');
        $result=$model->inserts($data);
        if($result){
            return json([
                'code'=>config('code.success'),
                'msg'=>'商品添加成功'
            ]);
        }else{
            return json([
                'code'=>config('code.fail'),
                'msg'=>'商品添加失败'
            ]);
        }
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        $data=$this->request->get();
        $model=model('Goods');
        $result=$model->finds($id);
        if($result){
            return json([
                'code'=>config('code.success'),
                'msg'=>'商品展示成功',
                'data'=>$result
            ]);
        }else{
            return json([
                'code'=>config('code.fail'),
                'msg'=>'商品展示失败',
                'data'=>[]
            ]);
        }
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        $data=$this->request->put();
        $model=model('Goods');
        $result=$model->updates($data,$id);
        return json([
            'code'=>config('code.success'),
            'msg'=>'修改成功'
        ]);
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        $model=model('Goods');
        $result=$model->deletes($id);
        if($result){
            return json([
                'code'=>config('code.success'),
                'msg'=>'删除成功'
            ]);
        }else{
            return json([
                'code'=>config('code.fail'),
                'msg'=>'删除失败'
            ]);
        }
    }

}
