<?php

namespace app\admin\controller;

use think\Controller;
use think\Db;
use think\Exception;
use think\Request;

class Team extends Controller
{
    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkJWT();
    }

    public function index()
    {
        try{
            $data=$this->request->get();
            if(isset($data['page'])&&!empty($data['page'])){
                $page=$data['page'];
            }else{
                $page=1;
            }

            if(isset($data['limit'])&&!empty($data['limit'])){
                $limit=$data['limit'];
            }else{
                $limit=1;
            }
            $sarr=[];
            if(!empty($data['tname'])){
                $sarr['tname']=['like','%'.$data['tname'].'%'];
            }
            $results=Db::table('team')->where($sarr)->order('tid','desc')
                ->alias('t')
                ->join('category c','t.cid=c.cid')
                ->field('t.*,c.cname')
                ->paginate($limit,false,[
                    'page'=>$page
                ]);
            $total=$results->total();
            $datas=$results->items();
            if($datas){
                return json([
                    'code'=>config('code.success'),
                    'msg'=>'团队数据获取成功',
                    'data'=>$datas,
                    'total'=>$total
                ]);
            }else{
                return json([
                    'code'=>config('code.success'),
                    'msg'=>'暂无团队',
                    'data'=>[]
                ]);
            }
        }catch (Exception $exception){
            return json([
                'code'=>config('code.fail'),
                'msg'=>'获取团队数据失败',
            ]);
        }
    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        $data=$this->request->post();
        $model=model('Team');
        $result=$model->inserts($data);
        if($result){
           return json([
               'code'=>config('code.success'),
               'msg'=>'团队添加成功'
           ]);
        }else{
            return json([
                'code'=>config('code.fail'),
                'msg'=>'团队添加失败'
            ]);
        }
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
        $model=model('Team');
        $result=$model->finds($id);
        if($result){
            return json([
                'code'=>config('code.success'),
                'msg'=>'团队展示成功',
                'data'=>$result
            ]);
        }else{
            return json([
                'code'=>config('code.fail'),
                'msg'=>'团队展示失败',
                'data'=>[]
            ]);
        }
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        $data=$this->request->put();
        $model=model('Team');
        $team=$model->queryones($data);
        if($team){
            return json([
                'code'=>config('code.fail'),
                'msg'=>'团队信息已存在，未能做修改'
            ]);
        }
        $result=$model->updates($data,$id);
        if($result){
            return json([
                'code'=>config('code.success'),
                'msg'=>'修改成功'
            ]);
        }else{
            return json([
                'code'=>config('code.fail'),
                'msg'=>'修改失败'
            ]);
        }
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
        $model=model('Team');
        $result=$model->deletes($id);
        if($result){
            return json([
                'code'=>config('code.success'),
                'msg'=>'删除成功'
            ]);
        }else{
            return json([
                'code'=>config('code.fail'),
                'msg'=>'删除失败'
            ]);
        }
    }
}
